# nolint start
DataFrame <- S4Vectors::DataFrame
SummarizedExperiment <- SummarizedExperiment::SummarizedExperiment
assay <- SummarizedExperiment::assay
data.table <- data.table::data.table
iris <- datasets::iris
mtcars <- datasets::mtcars
rowData <- SummarizedExperiment::rowData
`rowData<-` <- SummarizedExperiment::`rowData<-`
sparseMatrix <- Matrix::sparseMatrix
tibble <- tibble::tibble
# nolint end
