test_that("isGitRepo", {
    x <- getwd()
    ok <- isGitRepo(x)
    expect_is(ok, "logical")
    ok <- isAGitRepo(x)
    expect_is(ok, "logical")
    ok <- allAreGitRepos(x)
    expect_is(ok, "logical")
    expect_false(isGitRepo(1L))
    expect_false(isAGitRepo(1L))
    expect_false(allAreGitRepos(1L))
})
